// Page names here reffers on ./nuxt/routes.json
export enum Pages {
  HOME = 'home',
  // ABOUT = 'about',
  // 'ABOUT-AWARDS' = 'about-awards',
  // 'ABOUT-BRAND' = 'about-our-brand',
  // 'ABOUT-PURPOSE' = 'about-values-and-purposes',
  // 'ABOUT-STRUCTURE' = 'about-our-structure',
  // 'ABOUT-TRAJECTORY' = 'about-our-trajectory',
  // BROKER = 'broker',
  // CAREERS = 'careers',
  // 'CAREERS-CULTURE' = 'careers-our-culture',
  // 'CAREERS-BENEFITS' = 'careers-our-benefits',
  // 'CAREERS-PROGRAMS' = 'careers-programs',
  // COMPANY = 'company',
  // 'CONTACT-US' = 'contact-us',
  // DENTIST = 'dentist',
  // ESG = 'esg',
  // PLANS = 'plans',
  // PRESS = 'press',
  // PROVIDER = 'provider',
  // PLACEHOLDER = 'placeholder',
  // 'FORM-ACCREDITED' = 'form-accredited',
  // BENEFICIARY = 'beneficiary',
  // 'TERMS-OF-USE' = 'terms-of-use',
  // 'PRIVACY-POLICY' = 'privacy-policy',
  // 'PRIVACY-PORTAL' = 'privacy-portal',
}

const ROUTES = {
  HOME: '/',
  // ABOUT: '/quem-somos/',
  // 'ABOUT-AWARDS': '/quem-somos/premios-e-certificacoes',
  // 'ABOUT-BRAND': '/quem-somos/nossa-marca',
  // 'ABOUT-PURPOSE': '/quem-somos/valores-e-propositos',
  // 'ABOUT-STRUCTURE': '/quem-somos/nossa-estrutura',
  // 'ABOUT-TRAJECTORY': '/quem-somos/nossa-trajetoria',
  // BROKER: '/corretor',
  // CAREERS: '/carreiras',
  // 'CAREERS-CULTURE': '/carreiras/nossa-cultura',
  // 'CAREERS-BENEFITS': '/carreiras/nossos-beneficios',
  // 'CAREERS-PROGRAMS': '/carreiras/programas',
  // COMPANY: '/empresa',
  // 'CONTACT-US': '/fale-conosco',
  // DENTIST: '/dentista',
  // ESG: '/sustentabilidade',
  // PLANS: '/planos',
  // PRESS: '/imprensa',
  // PROVIDER: '/fornecedores',
  // 'FORM-ACCREDITED': '/novo-credenciado',
  // BENEFICIARY: '/beneficiario',
  // 'TERMS-OF-USE': '/termos-de-uso',
  // 'PRIVACY-POLICY': '/politica-de-privacidade',
  // 'PRIVACY-PORTAL': '/portal-de-privacidade',
  // PLACEHOLDER: '',
} as const

export default ROUTES
